num_episodes: 2
output_dir: ./output

# Environment
obs_dim: 19
action_dim: 7
pred_horizon: 1
obs_horizon: 1
action_horizon: 1


# Training parameters
num_epochs: 1000
model_path: ./weights/lift_mlp_last.pt

train:
  loss:
    _target_: torch.nn.MSELoss

obs_keys: &obs_keys ['robot0_eef_pos', 'robot0_eef_quat', 'robot0_gripper_qpos', 'object']


env_runner: 
  _target_: imitation.env_runner.robomimic_lowdim_runner.RobomimicEnvRunner
  output_dir: ${output_dir}
  env:
    _target_: imitation.env.robomimic_lowdim_wrapper.RobomimicLowdimWrapper
    task: "Lift"

policy:
  _target_: imitation.policy.mlp_policy.MLPPolicy
  model:
    _target_: imitation.model.mlp.MLPNet
    input_dim: ${obs_dim}
    output_dim: ${action_dim}
    hidden_dims: [256, 256, 256, 256]
    activation:
      _target_: torch.nn.LeakyReLU
    output_activation: 
      _target_: torch.nn.Identity
  env: ${env_runner.env}
  dataset:
    _target_: imitation.dataset.robomimic_lowdim_dataset.RobomimicLowdimDataset
    dataset_path: ./data/lift/ph/low_dim_v141.hdf5
    obs_keys: *obs_keys
    pred_horizon: ${pred_horizon}
  ckpt_path: ${model_path}


agent:
  _target_: imitation.agent.robomimic_lowdim_agent.RobomimicLowdimAgent