_target_: imitation.policy.mlp_diffusion_policy.MLPDiffusionUnet1DPolicy
obs_dim: ${task.obs_dim}
action_dim: ${task.action_dim}
pred_horizon: ${pred_horizon}
obs_horizon: ${obs_horizon}
action_horizon: ${action_horizon}
num_diffusion_iters: 100
dataset: ${task.dataset}
ckpt_path: ./weights/mlp_diffusion_${task.task_name}.ckpt
lr: 0.0001