
task_name: &task_name transport
dataset_type: &dataset_type ph
dataset_path: &dataset_path ./data/${task.task_name}/${task.dataset_type}/low_dim_v141.hdf5


obs_dim: 71
action_dim: 14
pred_horizon: 1
obs_horizon: 1
action_horizon: 1


obs_keys: &obs_keys ['robot0_joint_pos_sin', 'robot0_joint_pos_cos', 'robot0_joint_vel', 'robot0_eef_pos', 'robot0_eef_quat', 'robot0_gripper_qpos', 'object'] # TODO add robot1 . . .
robots: &robots ["Panda", "Panda"]

env_runner: 
  _target_: imitation.env_runner.robomimic_lowdim_runner.RobomimicEnvRunner
  output_dir: ${output_dir}
  action_horizon: ${action_horizon}
  obs_horizon: ${obs_horizon}
  env:
    _target_: imitation.env.robomimic_lowdim_wrapper.RobomimicLowdimWrapper
    max_steps: ${max_steps}
    task: "TwoArmTransport"
    robots: *robots
    

dataset:
  _target_: imitation.dataset.robomimic_lowdim_dataset.RobomimicLowdimDataset
  dataset_path: ${task.dataset_path}
  obs_keys: *obs_keys
  pred_horizon: ${task.pred_horizon}